import { z } from 'zod';
import { LIMITS, MESSAGE_TYPES, type MessageType } from '../constants.js';
import type { AttachmentDto } from './media.js';
import type { PollDto } from './poll.js';
import type { CalendarEventDto } from './calendar.js';
import type { GameSessionDto } from './game.js';
import type { StickerDto } from './sticker.js';

export interface ReactionDto {
  emoji: string;
  userIds: string[];
}

/**
 * Structured extras for non-text messages. Everything is optional so that
 * additional message types introduced by future modules stay backwards
 * compatible with older clients (they fall back to rendering `body`).
 */
export interface MessageMetadata {
  stickerId?: string;
  pollId?: string;
  eventId?: string;
  gameSessionId?: string;
  forwardedFrom?: { conversationId: string; messageId: string };
  /** System messages: machine readable event describing what happened. */
  system?: { kind: string; actorId?: string; targetIds?: string[]; value?: string };
  /** Free-form space reserved for feature modules. Never dropped by the server. */
  module?: Record<string, unknown>;
}

export interface MessageDto {
  id: string;
  conversationId: string;
  senderId: string | null;
  type: MessageType;
  body: string | null;
  attachments: AttachmentDto[];
  replyToId: string | null;
  replyTo: MessageSnippet | null;
  metadata: MessageMetadata;
  reactions: ReactionDto[];
  clientId: string | null;
  createdAt: string;
  editedAt: string | null;
  deletedAt: string | null;
  /** Expanded entities so a chat renders in a single round trip. */
  poll?: PollDto;
  event?: CalendarEventDto;
  game?: GameSessionDto;
  sticker?: StickerDto;
}

export interface MessageSnippet {
  id: string;
  senderId: string | null;
  type: MessageType;
  body: string | null;
  attachmentKind: string | null;
  deletedAt: string | null;
}

export const messageMetadataSchema: z.ZodType<MessageMetadata> = z.object({
  stickerId: z.string().uuid().optional(),
  pollId: z.string().uuid().optional(),
  eventId: z.string().uuid().optional(),
  gameSessionId: z.string().uuid().optional(),
  forwardedFrom: z
    .object({ conversationId: z.string().uuid(), messageId: z.string().uuid() })
    .optional(),
  system: z
    .object({
      kind: z.string().max(64),
      actorId: z.string().uuid().optional(),
      targetIds: z.array(z.string().uuid()).max(100).optional(),
      value: z.string().max(500).optional(),
    })
    .optional(),
  module: z.record(z.unknown()).optional(),
});

export const sendMessageSchema = z
  .object({
    type: z.enum(MESSAGE_TYPES).default('text'),
    body: z.string().max(LIMITS.messageBodyMax).nullable().optional(),
    attachmentIds: z.array(z.string().uuid()).max(LIMITS.attachmentsPerMessage).optional(),
    replyToId: z.string().uuid().nullable().optional(),
    /** Idempotency key generated by the client; re-sends return the same message. */
    clientId: z.string().min(1).max(64).optional(),
    metadata: messageMetadataSchema.optional(),
  })
  .refine(
    (v) =>
      (v.body != null && v.body.trim().length > 0) ||
      (v.attachmentIds?.length ?? 0) > 0 ||
      v.metadata?.stickerId != null ||
      v.metadata?.pollId != null ||
      v.metadata?.eventId != null ||
      v.metadata?.gameSessionId != null,
    { message: 'message needs a body, an attachment or a referenced entity' },
  );
export type SendMessageInput = z.infer<typeof sendMessageSchema>;

export const editMessageSchema = z.object({
  body: z.string().min(1).max(LIMITS.messageBodyMax),
});

export const reactionSchema = z.object({
  emoji: z.string().min(1).max(16),
});

export const listMessagesSchema = z.object({
  limit: z.coerce.number().int().min(1).max(LIMITS.messagePageSizeMax).optional(),
  before: z.string().uuid().optional(),
  after: z.string().uuid().optional(),
});

export const searchMessagesSchema = z.object({
  q: z.string().trim().min(2).max(200),
  conversationId: z.string().uuid().optional(),
  limit: z.coerce.number().int().min(1).max(50).optional(),
});
