-- Initiative – initial schema.
-- All primary keys are UUID v7 generated by the application (time sortable),
-- so no database extension is required and Neon/Supabase/self-hosted Postgres
-- behave identically.

create table if not exists users (
  id                    uuid primary key,
  username              text        not null unique,
  display_name          text        not null,
  bio                   text,
  password_hash         text        not null,
  avatar_attachment_id  uuid,
  calendar_token        text        not null unique,
  settings              jsonb       not null default '{}'::jsonb,
  last_seen_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table if not exists refresh_tokens (
  id           uuid primary key,
  user_id      uuid        not null references users (id) on delete cascade,
  token_hash   text        not null unique,
  user_agent   text,
  expires_at   timestamptz not null,
  revoked_at   timestamptz,
  created_at   timestamptz not null default now()
);
create index if not exists refresh_tokens_user_idx on refresh_tokens (user_id);

create table if not exists push_subscriptions (
  id              uuid primary key,
  user_id         uuid        not null references users (id) on delete cascade,
  endpoint        text        not null unique,
  p256dh          text        not null,
  auth            text        not null,
  user_agent      text,
  failure_count   integer     not null default 0,
  last_success_at timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on push_subscriptions (user_id);

create table if not exists conversations (
  id                   uuid primary key,
  type                 text        not null check (type in ('direct', 'group')),
  title                text,
  avatar_attachment_id uuid,
  created_by           uuid references users (id) on delete set null,
  last_message_at      timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists conversations_last_message_idx on conversations (last_message_at desc nulls last);

create table if not exists conversation_members (
  conversation_id       uuid        not null references conversations (id) on delete cascade,
  user_id               uuid        not null references users (id) on delete cascade,
  role                  text        not null default 'member' check (role in ('owner', 'admin', 'member')),
  nickname              text,
  last_read_message_id  uuid,
  muted_until           timestamptz,
  archived              boolean     not null default false,
  joined_at             timestamptz not null default now(),
  primary key (conversation_id, user_id)
);
create index if not exists conversation_members_user_idx on conversation_members (user_id);

create table if not exists messages (
  id              uuid primary key,
  conversation_id uuid        not null references conversations (id) on delete cascade,
  sender_id       uuid references users (id) on delete set null,
  type            text        not null default 'text',
  body            text,
  reply_to_id     uuid references messages (id) on delete set null,
  metadata        jsonb       not null default '{}'::jsonb,
  client_id       text,
  created_at      timestamptz not null default now(),
  edited_at       timestamptz,
  deleted_at      timestamptz
);
create index if not exists messages_conversation_idx on messages (conversation_id, id desc);
create unique index if not exists messages_client_id_idx
  on messages (conversation_id, sender_id, client_id)
  where client_id is not null;
create index if not exists messages_body_fts_idx
  on messages using gin (to_tsvector('simple', coalesce(body, '')));

create table if not exists attachments (
  id               uuid primary key,
  message_id       uuid references messages (id) on delete cascade,
  uploader_id      uuid references users (id) on delete set null,
  kind             text        not null check (kind in ('image', 'video', 'audio', 'file', 'sticker')),
  mime             text        not null,
  size             bigint      not null default 0,
  file_name        text,
  storage_key      text        not null,
  width            integer,
  height           integer,
  duration_ms      integer,
  waveform         jsonb,
  preview_data_url text,
  status           text        not null default 'pending' check (status in ('pending', 'ready')),
  created_at       timestamptz not null default now()
);
create index if not exists attachments_message_idx on attachments (message_id);
create index if not exists attachments_uploader_idx on attachments (uploader_id);

create table if not exists reactions (
  message_id uuid        not null references messages (id) on delete cascade,
  user_id    uuid        not null references users (id) on delete cascade,
  emoji      text        not null,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create table if not exists sticker_packs (
  id                uuid primary key,
  owner_id          uuid references users (id) on delete cascade,
  name              text        not null,
  cover_sticker_id  uuid,
  is_public         boolean     not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists sticker_packs_owner_idx on sticker_packs (owner_id);

create table if not exists stickers (
  id            uuid primary key,
  pack_id       uuid        not null references sticker_packs (id) on delete cascade,
  attachment_id uuid        not null references attachments (id) on delete cascade,
  emoji         text,
  width         integer     not null default 512,
  height        integer     not null default 512,
  position      integer     not null default 0,
  created_at    timestamptz not null default now()
);
create index if not exists stickers_pack_idx on stickers (pack_id, position);

create table if not exists sticker_pack_installs (
  pack_id      uuid        not null references sticker_packs (id) on delete cascade,
  user_id      uuid        not null references users (id) on delete cascade,
  installed_at timestamptz not null default now(),
  primary key (pack_id, user_id)
);

create table if not exists polls (
  id                uuid primary key,
  conversation_id   uuid        not null references conversations (id) on delete cascade,
  message_id        uuid references messages (id) on delete set null,
  created_by        uuid references users (id) on delete set null,
  kind              text        not null default 'choice' check (kind in ('choice', 'date')),
  question          text        not null,
  description       text,
  multiple          boolean     not null default false,
  anonymous         boolean     not null default false,
  allow_add_options boolean     not null default false,
  closes_at         timestamptz,
  closed_at         timestamptz,
  created_event_id  uuid,
  created_at        timestamptz not null default now()
);
create index if not exists polls_conversation_idx on polls (conversation_id);

create table if not exists poll_options (
  id         uuid primary key,
  poll_id    uuid    not null references polls (id) on delete cascade,
  label      text,
  starts_at  timestamptz,
  ends_at    timestamptz,
  position   integer not null default 0,
  created_by uuid references users (id) on delete set null
);
create index if not exists poll_options_poll_idx on poll_options (poll_id, position);

create table if not exists poll_votes (
  poll_id   uuid        not null references polls (id) on delete cascade,
  option_id uuid        not null references poll_options (id) on delete cascade,
  user_id   uuid        not null references users (id) on delete cascade,
  value     text        not null default 'yes' check (value in ('yes', 'no', 'maybe')),
  voted_at  timestamptz not null default now(),
  primary key (poll_id, option_id, user_id)
);
create index if not exists poll_votes_option_idx on poll_votes (option_id);

create table if not exists calendar_events (
  id               uuid primary key,
  conversation_id  uuid references conversations (id) on delete cascade,
  created_by       uuid references users (id) on delete set null,
  message_id       uuid references messages (id) on delete set null,
  title            text        not null,
  description      text,
  location         text,
  starts_at        timestamptz not null,
  ends_at          timestamptz not null,
  all_day          boolean     not null default false,
  rrule            text,
  color            text,
  reminder_minutes jsonb       not null default '[]'::jsonb,
  source_poll_id   uuid references polls (id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz
);
create index if not exists calendar_events_conversation_idx on calendar_events (conversation_id);
create index if not exists calendar_events_window_idx on calendar_events (starts_at, ends_at);

create table if not exists event_attendees (
  event_id     uuid        not null references calendar_events (id) on delete cascade,
  user_id      uuid        not null references users (id) on delete cascade,
  status       text        not null default 'pending' check (status in ('yes', 'no', 'maybe', 'pending')),
  responded_at timestamptz,
  primary key (event_id, user_id)
);
create index if not exists event_attendees_user_idx on event_attendees (user_id);

create table if not exists game_sessions (
  id              uuid primary key,
  conversation_id uuid        not null references conversations (id) on delete cascade,
  message_id      uuid references messages (id) on delete set null,
  game_key        text        not null,
  status          text        not null default 'open' check (status in ('open', 'active', 'finished', 'aborted')),
  state           jsonb       not null default '{}'::jsonb,
  players         jsonb       not null default '[]'::jsonb,
  turn_user_id    uuid references users (id) on delete set null,
  winner_user_ids jsonb       not null default '[]'::jsonb,
  version         integer     not null default 0,
  created_by      uuid references users (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists game_sessions_conversation_idx on game_sessions (conversation_id);

-- Deferred foreign keys (the referenced tables are created later above).
do $$
begin
  alter table users
    add constraint users_avatar_attachment_fk
    foreign key (avatar_attachment_id) references attachments (id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table conversations
    add constraint conversations_avatar_attachment_fk
    foreign key (avatar_attachment_id) references attachments (id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table polls
    add constraint polls_created_event_fk
    foreign key (created_event_id) references calendar_events (id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table sticker_packs
    add constraint sticker_packs_cover_fk
    foreign key (cover_sticker_id) references stickers (id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter table conversation_members
    add constraint conversation_members_last_read_fk
    foreign key (last_read_message_id) references messages (id) on delete set null;
exception when duplicate_object then null;
end $$;
