import { call, konto, in3Tagen } from './lib.mjs';
import { execSync } from 'node:child_process';
const sql = (q) => execSync(`psql "${process.env.DATABASE_URL}" -At -c "${q}"`).toString().trim();
const a = await konto('pfbus'), b = await konto('pfbusb');
const pre = 'pfbusx' + Math.random().toString(36).slice(2, 7);
const N = Number(process.argv[2] ?? 120);
sql(`insert into users (id, username, display_name, password_hash, calendar_token) select gen_random_uuid(), '${pre}'||i, '${pre}'||i, 'x', gen_random_uuid()::text from generate_series(1,${N}) i`);
const fake = sql(`select id from users where username like '${pre}%'`).split('\n');
const base = 'ws://localhost:8080/ws';
const frames = [];
const ws = new WebSocket(`${base}?token=${b.token}`);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
ws.onmessage = (m) => { const f = JSON.parse(m.data); if (f.type !== 'pong' && f.type !== 'hello') frames.push(f); };
const wsA = new WebSocket(`${base}?token=${a.token}`);
const framesA = [];
await new Promise((res, rej) => { wsA.onopen = res; wsA.onerror = rej; });
wsA.onmessage = (m) => { const f = JSON.parse(m.data); if (f.type !== 'pong' && f.type !== 'hello') framesA.push(f); };
let r = await call('POST', '/calendar/events', a.token, { title: 'Bus gross', ...in3Tagen(), attendeeIds: [b.id, ...fake], zustellung: { einzelchats: false, gruppenChatIds: [] } });
console.log('anlegen', r.status, 'attendees', r.body.attendees?.length, JSON.stringify(r.body.zustellung));
const id = r.body.id;
await new Promise(r => setTimeout(r, 1500));
console.log('B Rahmen nach Anlegen:', frames.map(f => f.type + (f.payload?.eventId ? ' eventId' : '') + (f.payload?.scope ? ' scope=' + f.payload.scope : '') + (f.payload?.event?.stand != null ? ' stand=' + f.payload.event.stand : '')));
console.log('A Rahmen nach Anlegen:', framesA.map(f => f.type + (f.payload?.eventId ? ' eventId' : '') + (f.payload?.scope ? ' scope=' + f.payload.scope : '')));
frames.length = 0; framesA.length = 0;
r = await call('POST', `/calendar/events/${id}/rsvp`, b.token, { status: 'yes' });
console.log('rsvp', r.status, 'stand', r.body.stand);
await new Promise(r => setTimeout(r, 1500));
console.log('B Rahmen nach rsvp:', frames.map(f => f.type + (f.payload?.eventId ? ' eventId=' + f.payload.eventId.slice(0,8) : '') + (f.payload?.scope ? ' scope=' + f.payload.scope : '') + (f.payload?.event?.stand != null ? ' stand=' + f.payload.event.stand : '')));
console.log('A Rahmen nach rsvp:', framesA.map(f => f.type + (f.payload?.eventId ? ' eventId=' + f.payload.eventId.slice(0,8) : '') + (f.payload?.scope ? ' scope=' + f.payload.scope : '') + (f.payload?.event?.stand != null ? ' stand=' + f.payload.event.stand : '')));
frames.length = 0;
r = await call('DELETE', `/calendar/events/${id}`, a.token);
await new Promise(r => setTimeout(r, 1500));
console.log('delete', r.status, 'B Rahmen:', frames.map(f => f.type + (f.payload?.grund ?? '') + (f.payload?.scope ? ' scope=' + f.payload.scope : '')));
ws.close(); wsA.close();
sql(`delete from calendar_events where id='${id}'`);
sql(`delete from users where username like '${pre}%' or id in ('${a.id}','${b.id}')`);
sql(`delete from conversations c where not exists (select 1 from conversation_members m where m.conversation_id=c.id)`);
